### ISSUE TITLE
RuntimeError: No CUDA GPUs are available

### ISSUE THREAD

**Issue by f-amerehi** [LiYingwei/ShapeTextureDebiasedTraining#12]
Hi @LiYingwei  hope that is well.

When I run `torch.cuda.is_available()` it shows `true`. And Cuda is always work fine in all projects that need GPU. However, in this project when I run `python imagenet.py -a resnet50 --data %DATA% --mixbn --evaluate --load %CKPT%` , it returns `RuntimeError: No CUDA GPUs are available`

Could you please give me some clue? 
Thanks

**Comment by LiuShisan23** [comment]
maybe you should replace the arg.gpu_id with your real gpu_id such as "0"

**Comment by f-amerehi** [comment]
Thanks @LiuShisan23 Yes, it's already [resolved](https://github.com/LiYingwei/ShapeTextureDebiasedTraining/pull/14).
