### ISSUE TITLE
imagenet-a

### ISSUE THREAD

**Issue by jieweilai** [LiYingwei/ShapeTextureDebiasedTraining#3]
hello,i have a quession,if you test your model in imagenet-a directly?i find the classes in imagenet-a is different from imagenet-200?how do you slove it?

**Comment by LiYingwei** [comment]
For the models trained on ImageNet-200, we don't test them on ImageNet-A. We only test the **ImageNet-1000** trained model on Imagenet-A. [This script](https://github.com/hendrycks/natural-adv-examples/blob/master/eval.py) tells you how to do it.

**Comment by jieweilai** [comment]
thanks for your reply,i thanks you very much!



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LiYingwei/ShapeTextureDebiasedTraining"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月24日(星期二) 晚上9:09
收件人:&nbsp;"LiYingwei/ShapeTextureDebiasedTraining"<ShapeTextureDebiasedTraining@noreply.github.com&gt;;
抄送:&nbsp;"『☆初陽卍綻放』"<2556004343@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [LiYingwei/ShapeTextureDebiasedTraining] imagenet-a (#3)





 
For the models trained on ImageNet-200, we don't test them on ImageNet-A. We only test the ImageNet-1000 trained model on Imagenet-A. This script tells you how to do it.
