### ISSUE TITLE
FGSM Attack

### ISSUE THREAD

**Issue by GeJulia** [LiYingwei/ShapeTextureDebiasedTraining#5]
Hey, could you provide the schedule of how you tested the FGSM attack against your model? 
Did you generate from all ImageNet Test images and run afterwards the classification task? Or did you use another procedure?

Thanks! :)

**Comment by LiYingwei** [comment]
Basically, given an ImageNet test image, we first generate the adversarial example via FGSM, and then test the generated adversarial example to see if the model could correctly classify it. You could check the code [here](https://github.com/LiYingwei/ShapeTextureDebiasedTraining/blob/fe2b1d01b7d4c89b18164754730dfbc6b67e5977/imagenet.py#L561) to see the details.
